# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://help.github.com/actions/language-and-framework-guides/publishing-nodejs-packages

name: Change validator

on: 
  workflow_call:
  workflow_dispatch:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  linux:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout project
        uses: actions/checkout@v2
      - name: Node setup
        uses: actions/setup-node@v2
        with:
          node-version: 16
      - name: Setup project
        run: npm i
      - name: Create package
        run: npm pack
      - name: Run unit tests and system test
        run: npm test -- --coverage
  windows:
    runs-on: windows-latest
    steps:
      - name: Checkout project
        uses: actions/checkout@v2
      - name: Node setup
        uses: actions/setup-node@v2
        with:
          node-version: 16
      - name: Setup project
        run: npm i
      - name: Run unit tests and system test
        run: npm test -- --coverage
  mac:
    runs-on: macos-latest
    steps:
      - name: Checkout project
        uses: actions/checkout@v2
      - name: Node setup
        uses: actions/setup-node@v2
        with:
          node-version: 16
      - name: Setup project
        run: npm i
      - name: Run unit tests and system test
        run: npm test -- --coverage
