name: test

on: 
  workflow_call:
  workflow_dispatch:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  linux:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout project
        uses: actions/checkout@v2
      - name: Node setup
        uses: actions/setup-node@v2
        with:
          node-version: 16
      - name: Setup project
        run: npm i
      - name: Create Package
        run: npm pack
      - name: Extract Package Version
        uses: Saionaro/extract-package-version@v1.1.1
        id: packageVersion
      - name: Install package
        run: echo ${{steps.packageVersion.outputs.*}}
      - name: Run unit tests and system test
        run: npm test -- --coverage
